spring:
  datasource:
    driver-class-name : org.postgresql.Driver
    url : jdbc:postgresql://localhost:5432/relations
    username : postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    user:
      name: admin
      password: <PASSWORD>
server:
  port: 8084
